//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGG.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGG.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] _100001 {
            get {
                object obj = ResourceManager.GetObject("_100001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] _100002 {
            get {
                object obj = ResourceManager.GetObject("_100002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] _100003 {
            get {
                object obj = ResourceManager.GetObject("_100003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] _100004 {
            get {
                object obj = ResourceManager.GetObject("_100004", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] _100005 {
            get {
                object obj = ResourceManager.GetObject("_100005", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] _100006 {
            get {
                object obj = ResourceManager.GetObject("_100006", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] _900001 {
            get {
                object obj = ResourceManager.GetObject("_900001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] _900002 {
            get {
                object obj = ResourceManager.GetObject("_900002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] _900003 {
            get {
                object obj = ResourceManager.GetObject("_900003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] _900004 {
            get {
                object obj = ResourceManager.GetObject("_900004", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ActivityPay {
            get {
                object obj = ResourceManager.GetObject("ActivityPay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ArenaRankingReward {
            get {
                object obj = ResourceManager.GetObject("ArenaRankingReward", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ArmyType {
            get {
                object obj = ResourceManager.GetObject("ArmyType", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] BuildingBossReward {
            get {
                object obj = ResourceManager.GetObject("BuildingBossReward", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] BuildingReward {
            get {
                object obj = ResourceManager.GetObject("BuildingReward", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] BuildProbability {
            get {
                object obj = ResourceManager.GetObject("BuildProbability", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] BusinessArea {
            get {
                object obj = ResourceManager.GetObject("BusinessArea", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] BusinessCarPart {
            get {
                object obj = ResourceManager.GetObject("BusinessCarPart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] BusinessCity {
            get {
                object obj = ResourceManager.GetObject("BusinessCity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] BusinessGoods {
            get {
                object obj = ResourceManager.GetObject("BusinessGoods", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] BusinessGoodsPrice {
            get {
                object obj = ResourceManager.GetObject("BusinessGoodsPrice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] BuyPower {
            get {
                object obj = ResourceManager.GetObject("BuyPower", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] CeLue {
            get {
                object obj = ResourceManager.GetObject("CeLue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] CityResource {
            get {
                object obj = ResourceManager.GetObject("CityResource", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] CollectGoodsBuild {
            get {
                object obj = ResourceManager.GetObject("CollectGoodsBuild", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] CollectGoodsSiege {
            get {
                object obj = ResourceManager.GetObject("CollectGoodsSiege", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] CopyFamePass {
            get {
                object obj = ResourceManager.GetObject("CopyFamePass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DaMingLog {
            get {
                object obj = ResourceManager.GetObject("DaMingLog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///DROP TABLE  [dbo].[tg_activity_building]
        ///DROP TABLE  [dbo].[tg_arena]
        ///DROP TABLE  [dbo].[tg_arena_reports]
        ///DROP TABLE  [dbo].[tg_bag]
        ///DROP TABLE  [dbo].[tg_bag_log]
        ///DROP TABLE  [dbo].[tg_car]
        ///DROP TABLE  [dbo].[tg_duplicate_checkpoint]
        ///DROP TABLE  [dbo].[tg_duplicate_shot]
        ///DROP TABLE  [dbo].[tg_family]
        ///DROP TABLE  [dbo].[tg_family_apply]
        ///DROP TABLE  [dbo].[tg_family_log]
        ///DROP TABLE  [dbo].[tg_family_member]
        ///DROP TABLE  [dbo].[tg_fight_personal]
        ///DROP TABLE  [dbo].[tg_fight_yin]
        ///DROP TABLE  [d [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DuplicateReward {
            get {
                object obj = ResourceManager.GetObject("DuplicateReward", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] EntryPointSiege {
            get {
                object obj = ResourceManager.GetObject("EntryPointSiege", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Equip {
            get {
                object obj = ResourceManager.GetObject("Equip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] EquipAttRate {
            get {
                object obj = ResourceManager.GetObject("EquipAttRate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] EquipRate {
            get {
                object obj = ResourceManager.GetObject("EquipRate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] FamilyBadge {
            get {
                object obj = ResourceManager.GetObject("FamilyBadge", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] FamilyLevel {
            get {
                object obj = ResourceManager.GetObject("FamilyLevel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] FamilyLog {
            get {
                object obj = ResourceManager.GetObject("FamilyLog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] FamilyPost {
            get {
                object obj = ResourceManager.GetObject("FamilyPost", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] FightSkill {
            get {
                object obj = ResourceManager.GetObject("FightSkill", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] FightSkillEffect {
            get {
                object obj = ResourceManager.GetObject("FightSkillEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 毛泽东,周恩来,刘少奇,朱德,彭德怀,林彪,刘伯承,陈毅,贺龙,聂荣臻,徐向前,罗荣桓,叶剑英,李大钊,陈独秀,孙中山,孙文,孙逸仙,邓小平,陈云,江泽民,李鹏,朱镕基,李瑞环,尉健行,李岚清,胡锦涛,罗干,温家宝,吴邦国,曾庆红,贾庆林,黄菊,吴官正,李长春,吴仪,回良玉,曾培炎,周永康,曹刚川,唐家璇,华建敏,陈至立,陈良宇,张德江,张立昌,俞正声,王乐泉,刘云山,王刚,王兆国,刘淇,贺国强,郭伯雄,胡耀邦,李登辉,连战,陈水扁,宋楚瑜,吕秀莲,郁慕明,蒋介石,蒋中正,蒋经国,马英九,习近平,李克强,吴帮国,无帮国,无邦国,无帮过,瘟家宝,假庆林,甲庆林,假青林,离长春,习远平,袭近平,李磕墙,贺过墙,和锅枪,粥永康,轴永康,肘永康,周健康,粥健康,周小康,姜异康,孙政才,令计划,陆 昊,范长龙,许其亮,马凯,王岐山,王沪宁,刘延东,刘奇葆,孙春兰,李建国,李源潮,汪洋,张春贤,张高丽,孟建柱,赵乐际,胡春华,栗战书,郭金龙,韩正,杜青林,赵洪祝,杨晶,徐才厚,万里,乔石,宋平,何勇,于广洲,马飚,马兴瑞,马晓天,王君,王侠,王珉,王勇,王晨,王毅,王三运,王万宾,王玉普,王正伟,王东明,王光亚,王伟光, [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string filterwords {
            get {
                return ResourceManager.GetString("filterwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Fusion {
            get {
                object obj = ResourceManager.GetObject("Fusion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] GameGoods {
            get {
                object obj = ResourceManager.GetObject("GameGoods", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] HeZhanSkill {
            get {
                object obj = ResourceManager.GetObject("HeZhanSkill", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] HeZhanSkillEffect {
            get {
                object obj = ResourceManager.GetObject("HeZhanSkillEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] HeZhanStreng {
            get {
                object obj = ResourceManager.GetObject("HeZhanStreng", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Identity {
            get {
                object obj = ResourceManager.GetObject("Identity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] InfluenceFeature {
            get {
                object obj = ResourceManager.GetObject("InfluenceFeature", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] LandInfo {
            get {
                object obj = ResourceManager.GetObject("LandInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] LandPool {
            get {
                object obj = ResourceManager.GetObject("LandPool", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] LifeSkill {
            get {
                object obj = ResourceManager.GetObject("LifeSkill", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] LifeSkillEffect {
            get {
                object obj = ResourceManager.GetObject("LifeSkillEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;modules&gt;
        ///  &lt;module name=&quot;定时任务&quot; type=&quot;0&quot; value=&quot;TGG.Module.Timer&quot; order=&quot;0&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;通信系统&quot; type=&quot;0&quot; value=&quot;TGG.Module.Socket&quot; order=&quot;1&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;地图系统&quot; type=&quot;1&quot; value=&quot;TGG.Module.Scene&quot; order=&quot;1&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;用户系统&quot; type=&quot;1&quot; value=&quot;TGG.Module.User&quot; order=&quot;2&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;跑商系统&quot; type=&quot;1&quot; value=&quot;TGG.Module.Business&quot; order=&quot;3&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;道具系统&quot; type=&quot;1&quot; value=&quot;TGG.Module.Props&quot; order=&quot;4&quot;&gt;&lt;/modu [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string module {
            get {
                return ResourceManager.GetString("module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ModuleOpen {
            get {
                object obj = ResourceManager.GetObject("ModuleOpen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;modules&gt;
        ///  &lt;module name=&quot;USER&quot; value=&quot;GMQ_USER&quot; order=&quot;1&quot; type=&quot;0&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;BUSINESS&quot; value=&quot;GMQ_BUSINESS&quot; order=&quot;2&quot; type=&quot;0&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;SCENE&quot; value=&quot;GMQ_SCENE&quot; order=&quot;3&quot; type=&quot;0&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;BAG&quot; value=&quot;GMQ_PROP&quot; order=&quot;4&quot; type=&quot;0&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;TASK&quot; value=&quot;GMQ_TASK&quot; order=&quot;5&quot; type=&quot;0&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;EQUIP&quot; value=&quot;GMQ_EQUIP&quot; order=&quot;6&quot; type=&quot;0&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;ROLE&quot; value=&quot;GMQ_RO [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string modulequeue {
            get {
                return ResourceManager.GetString("modulequeue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Npc {
            get {
                object obj = ResourceManager.GetObject("Npc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] NpcArmy {
            get {
                object obj = ResourceManager.GetObject("NpcArmy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] NpcBuild {
            get {
                object obj = ResourceManager.GetObject("NpcBuild", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] NpcHire {
            get {
                object obj = ResourceManager.GetObject("NpcHire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] NpcMonster {
            get {
                object obj = ResourceManager.GetObject("NpcMonster", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] NpcRole {
            get {
                object obj = ResourceManager.GetObject("NpcRole", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] NpcSiege {
            get {
                object obj = ResourceManager.GetObject("NpcSiege", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Office {
            get {
                object obj = ResourceManager.GetObject("Office", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Prop {
            get {
                object obj = ResourceManager.GetObject("Prop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] RecruitRate {
            get {
                object obj = ResourceManager.GetObject("RecruitRate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] RoleBornPoint {
            get {
                object obj = ResourceManager.GetObject("RoleBornPoint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] RoleCollect {
            get {
                object obj = ResourceManager.GetObject("RoleCollect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] RoleGroup {
            get {
                object obj = ResourceManager.GetObject("RoleGroup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] RoleHome {
            get {
                object obj = ResourceManager.GetObject("RoleHome", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] RoleInfo {
            get {
                object obj = ResourceManager.GetObject("RoleInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] RoleLvUpdate {
            get {
                object obj = ResourceManager.GetObject("RoleLvUpdate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] RoleTitle {
            get {
                object obj = ResourceManager.GetObject("RoleTitle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Rule {
            get {
                object obj = ResourceManager.GetObject("Rule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Scene {
            get {
                object obj = ResourceManager.GetObject("Scene", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] shakeMoneyTree {
            get {
                object obj = ResourceManager.GetObject("shakeMoneyTree", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Siege {
            get {
                object obj = ResourceManager.GetObject("Siege", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] SiegeBossReward {
            get {
                object obj = ResourceManager.GetObject("SiegeBossReward", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] SiegeReward {
            get {
                object obj = ResourceManager.GetObject("SiegeReward", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Spirit {
            get {
                object obj = ResourceManager.GetObject("Spirit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] StealAddProb {
            get {
                object obj = ResourceManager.GetObject("StealAddProb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TaskMain {
            get {
                object obj = ResourceManager.GetObject("TaskMain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TaskNpc {
            get {
                object obj = ResourceManager.GetObject("TaskNpc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TaskRetainers {
            get {
                object obj = ResourceManager.GetObject("TaskRetainers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TaskVocation {
            get {
                object obj = ResourceManager.GetObject("TaskVocation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TaskVocationProb {
            get {
                object obj = ResourceManager.GetObject("TaskVocationProb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[sp_user_keep]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [sp_user_keep]
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[sp_record_day]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///DROP PROCEDURE [sp_record_day]
        ///
        ///IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[sp_record_day]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///BEGIN
        ///EXEC dbo.sp_executesql @statement = N&apos;
        ///CREATE PROCEDURE [sp_record_day]
        ///AS
        ///BEGIN
        ///	DECLARE @_ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string tgg_script {
            get {
                return ResourceManager.GetString("tgg_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N&apos;[view_ranking_exp]&apos;))
        ///DROP VIEW view_ranking_exp
        ///IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N&apos;[view_war_partner]&apos;))
        ///DROP VIEW [view_war_partner]
        ///IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N&apos;[view_war_city]&apos;))
        ///DROP VIEW [view_war_city]
        ///IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N&apos;[view_user_role_task]&apos;))
        ///DROP VIEW [view_user_role_task]
        ///IF  EXISTS (SELECT * FROM sys.views WH [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string tgg_view {
            get {
                return ResourceManager.GetString("tgg_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TowerEloquence {
            get {
                object obj = ResourceManager.GetObject("TowerEloquence", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TowerEnemy {
            get {
                object obj = ResourceManager.GetObject("TowerEnemy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TowerGame {
            get {
                object obj = ResourceManager.GetObject("TowerGame", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TowerPass {
            get {
                object obj = ResourceManager.GetObject("TowerPass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TowerTea {
            get {
                object obj = ResourceManager.GetObject("TowerTea", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Train {
            get {
                object obj = ResourceManager.GetObject("Train", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Vip {
            get {
                object obj = ResourceManager.GetObject("Vip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Vocation {
            get {
                object obj = ResourceManager.GetObject("Vocation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] WarCity {
            get {
                object obj = ResourceManager.GetObject("WarCity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] WarCitySize {
            get {
                object obj = ResourceManager.GetObject("WarCitySize", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] WarCopy {
            get {
                object obj = ResourceManager.GetObject("WarCopy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] WarDefenseFront {
            get {
                object obj = ResourceManager.GetObject("WarDefenseFront", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] WarDefenseZhen {
            get {
                object obj = ResourceManager.GetObject("WarDefenseZhen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] WarModuleMap {
            get {
                object obj = ResourceManager.GetObject("WarModuleMap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] WarMonster {
            get {
                object obj = ResourceManager.GetObject("WarMonster", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] WarSoldierRelation {
            get {
                object obj = ResourceManager.GetObject("WarSoldierRelation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] YiJiangTao {
            get {
                object obj = ResourceManager.GetObject("YiJiangTao", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Yin {
            get {
                object obj = ResourceManager.GetObject("Yin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] YinEffect {
            get {
                object obj = ResourceManager.GetObject("YinEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] YouYiYuan {
            get {
                object obj = ResourceManager.GetObject("YouYiYuan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] YouYiYuanReward {
            get {
                object obj = ResourceManager.GetObject("YouYiYuanReward", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
