//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGG.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGG.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ArenaRankingReward {
            get {
                object obj = ResourceManager.GetObject("ArenaRankingReward", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] BuildingReward {
            get {
                object obj = ResourceManager.GetObject("BuildingReward", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] BuildProbability {
            get {
                object obj = ResourceManager.GetObject("BuildProbability", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] BusinessArea {
            get {
                object obj = ResourceManager.GetObject("BusinessArea", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] BusinessCarPart {
            get {
                object obj = ResourceManager.GetObject("BusinessCarPart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] BusinessCity {
            get {
                object obj = ResourceManager.GetObject("BusinessCity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] BusinessGoods {
            get {
                object obj = ResourceManager.GetObject("BusinessGoods", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] BusinessGoodsPrice {
            get {
                object obj = ResourceManager.GetObject("BusinessGoodsPrice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] BuyPower {
            get {
                object obj = ResourceManager.GetObject("BuyPower", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] CollectGoodsBuild {
            get {
                object obj = ResourceManager.GetObject("CollectGoodsBuild", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] CollectGoodsSiege {
            get {
                object obj = ResourceManager.GetObject("CollectGoodsSiege", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] CopyFamePass {
            get {
                object obj = ResourceManager.GetObject("CopyFamePass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] DaMingLog {
            get {
                object obj = ResourceManager.GetObject("DaMingLog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///DROP TABLE  [dbo].[tg_activity_building]
        ///DROP TABLE  [dbo].[tg_arena]
        ///DROP TABLE  [dbo].[tg_arena_reports]
        ///DROP TABLE  [dbo].[tg_bag]
        ///DROP TABLE  [dbo].[tg_bag_log]
        ///DROP TABLE  [dbo].[tg_car]
        ///DROP TABLE  [dbo].[tg_duplicate_checkpoint]
        ///DROP TABLE  [dbo].[tg_duplicate_shot]
        ///DROP TABLE  [dbo].[tg_family]
        ///DROP TABLE  [dbo].[tg_family_apply]
        ///DROP TABLE  [dbo].[tg_family_log]
        ///DROP TABLE  [dbo].[tg_family_member]
        ///DROP TABLE  [dbo].[tg_fight_personal]
        ///DROP TABLE  [dbo].[tg_fight_yin]
        ///DROP TABLE  [d [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] EntryPointSiege {
            get {
                object obj = ResourceManager.GetObject("EntryPointSiege", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Equip {
            get {
                object obj = ResourceManager.GetObject("Equip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] EquipAttRate {
            get {
                object obj = ResourceManager.GetObject("EquipAttRate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] EquipRate {
            get {
                object obj = ResourceManager.GetObject("EquipRate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] FamilyBadge {
            get {
                object obj = ResourceManager.GetObject("FamilyBadge", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] FamilyLevel {
            get {
                object obj = ResourceManager.GetObject("FamilyLevel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] FamilyLog {
            get {
                object obj = ResourceManager.GetObject("FamilyLog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] FamilyPost {
            get {
                object obj = ResourceManager.GetObject("FamilyPost", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] FightSkill {
            get {
                object obj = ResourceManager.GetObject("FightSkill", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] FightSkillEffect {
            get {
                object obj = ResourceManager.GetObject("FightSkillEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Identity {
            get {
                object obj = ResourceManager.GetObject("Identity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] LifeSkill {
            get {
                object obj = ResourceManager.GetObject("LifeSkill", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] LifeSkillEffect {
            get {
                object obj = ResourceManager.GetObject("LifeSkillEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;modules&gt;
        ///  &lt;module name=&quot;定时任务&quot; type=&quot;0&quot; value=&quot;TGG.Module.Timer&quot; order=&quot;0&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;通信系统&quot; type=&quot;0&quot; value=&quot;TGG.Module.Socket&quot; order=&quot;1&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;地图系统&quot; type=&quot;1&quot; value=&quot;TGG.Module.Scene&quot; order=&quot;1&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;用户系统&quot; type=&quot;1&quot; value=&quot;TGG.Module.User&quot; order=&quot;2&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;跑商系统&quot; type=&quot;1&quot; value=&quot;TGG.Module.Business&quot; order=&quot;3&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;道具系统&quot; type=&quot;1&quot; value=&quot;TGG.Module.Props&quot; order=&quot;4&quot;&gt;&lt;/modu [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string module {
            get {
                return ResourceManager.GetString("module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ModuleOpen {
            get {
                object obj = ResourceManager.GetObject("ModuleOpen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;modules&gt;
        ///  &lt;module name=&quot;USER&quot; value=&quot;GMQ_USER&quot; order=&quot;1&quot; type=&quot;0&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;BUSINESS&quot; value=&quot;GMQ_BUSINESS&quot; order=&quot;2&quot; type=&quot;0&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;SCENE&quot; value=&quot;GMQ_SCENE&quot; order=&quot;3&quot; type=&quot;0&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;BAG&quot; value=&quot;GMQ_PROP&quot; order=&quot;4&quot; type=&quot;0&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;TASK&quot; value=&quot;GMQ_TASK&quot; order=&quot;5&quot; type=&quot;0&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;EQUIP&quot; value=&quot;GMQ_EQUIP&quot; order=&quot;6&quot; type=&quot;0&quot;&gt;&lt;/module&gt;
        ///  &lt;module name=&quot;ROLE&quot; value=&quot;GMQ_RO [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string modulequeue {
            get {
                return ResourceManager.GetString("modulequeue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Npc {
            get {
                object obj = ResourceManager.GetObject("Npc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] NpcArmy {
            get {
                object obj = ResourceManager.GetObject("NpcArmy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] NpcBuild {
            get {
                object obj = ResourceManager.GetObject("NpcBuild", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] NpcHire {
            get {
                object obj = ResourceManager.GetObject("NpcHire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] NpcMonster {
            get {
                object obj = ResourceManager.GetObject("NpcMonster", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] NpcRole {
            get {
                object obj = ResourceManager.GetObject("NpcRole", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] NpcSiege {
            get {
                object obj = ResourceManager.GetObject("NpcSiege", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Prop {
            get {
                object obj = ResourceManager.GetObject("Prop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] RecruitRate {
            get {
                object obj = ResourceManager.GetObject("RecruitRate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] RoleBornPoint {
            get {
                object obj = ResourceManager.GetObject("RoleBornPoint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] RoleGroup {
            get {
                object obj = ResourceManager.GetObject("RoleGroup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] RoleHome {
            get {
                object obj = ResourceManager.GetObject("RoleHome", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] RoleInfo {
            get {
                object obj = ResourceManager.GetObject("RoleInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] RoleLvUpdate {
            get {
                object obj = ResourceManager.GetObject("RoleLvUpdate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] RoleTitle {
            get {
                object obj = ResourceManager.GetObject("RoleTitle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Rule {
            get {
                object obj = ResourceManager.GetObject("Rule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Scene {
            get {
                object obj = ResourceManager.GetObject("Scene", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Siege {
            get {
                object obj = ResourceManager.GetObject("Siege", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] SiegeBossReward {
            get {
                object obj = ResourceManager.GetObject("SiegeBossReward", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] SiegeReward {
            get {
                object obj = ResourceManager.GetObject("SiegeReward", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Spirit {
            get {
                object obj = ResourceManager.GetObject("Spirit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] StealAddProb {
            get {
                object obj = ResourceManager.GetObject("StealAddProb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TaskMain {
            get {
                object obj = ResourceManager.GetObject("TaskMain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TaskNpc {
            get {
                object obj = ResourceManager.GetObject("TaskNpc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TaskRetainers {
            get {
                object obj = ResourceManager.GetObject("TaskRetainers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TaskVocation {
            get {
                object obj = ResourceManager.GetObject("TaskVocation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TaskVocationProb {
            get {
                object obj = ResourceManager.GetObject("TaskVocationProb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N&apos;[view_user_role_task]&apos;))
        ///DROP VIEW [view_user_role_task]
        ///IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N&apos;[view_user_role_friend]&apos;))
        ///DROP VIEW [view_user_role_friend]
        ///IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N&apos;[view_user_role_family_member]&apos;))
        ///DROP VIEW [view_user_role_family_member]
        ///IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N&apos;[view_user_role_family_apply]&apos;))
        ///DROP VIEW [view [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string tgg_view {
            get {
                return ResourceManager.GetString("tgg_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TowerEloquence {
            get {
                object obj = ResourceManager.GetObject("TowerEloquence", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TowerEnemy {
            get {
                object obj = ResourceManager.GetObject("TowerEnemy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TowerGame {
            get {
                object obj = ResourceManager.GetObject("TowerGame", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TowerPass {
            get {
                object obj = ResourceManager.GetObject("TowerPass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] TowerTea {
            get {
                object obj = ResourceManager.GetObject("TowerTea", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Train {
            get {
                object obj = ResourceManager.GetObject("Train", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Vip {
            get {
                object obj = ResourceManager.GetObject("Vip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Vocation {
            get {
                object obj = ResourceManager.GetObject("Vocation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] YiJiangTao {
            get {
                object obj = ResourceManager.GetObject("YiJiangTao", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Yin {
            get {
                object obj = ResourceManager.GetObject("Yin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] YinEffect {
            get {
                object obj = ResourceManager.GetObject("YinEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] YouYiYuan {
            get {
                object obj = ResourceManager.GetObject("YouYiYuan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] YouYiYuanReward {
            get {
                object obj = ResourceManager.GetObject("YouYiYuanReward", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
